spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/schoolDB?createDatabaseIfNotExist=true&useSSL=false
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: anywr_secret
